**Step-1:Import packages**

In [1]:
import pandas as pd               #dataframes
import numpy as np                #mathematical
import matplotlib.pyplot as plt   #graphs and visualization
import seaborn as sns

**Step-2: Create a Dataframe(Df) using list**

In [2]:
names=['Ramesh','Suresh','Sathish']
#pd.DataFrame(data,index,columns) here data,index,columns should be array form it is given in docstring
pd.DataFrame(names)

         0
0   Ramesh
1   Suresh
2  Sathish

In [3]:
# list,array,dict,tuple are iterable

**Step-3:I want to change the index**

In [4]:
names=['Ramesh','Suresh','Sathish']
ids=['A','B','C']
pd.DataFrame(names,ids)
#pd.DataFrame(data,index)

         0
A   Ramesh
B   Suresh
C  Sathish

**Step-4:add the columns**

In [5]:
names=['Ramesh','Suresh','Sathish']
ids=['A','B','C']
cols=['Names']
pd.DataFrame(names,ids,cols)

     Names
A   Ramesh
B   Suresh
C  Sathish

**Step-5: Data and columns(we should definitely provide argument name)**

In [6]:
names=['Ramesh','Suresh','Sathish']
cols=['Names']
pd.DataFrame(names,columns=cols)

     Names
0   Ramesh
1   Suresh
2  Sathish

**Step-6: Multiple columns**

In [7]:
names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
pd.DataFrame(names,age)
#pd.Dataframe(data,index)

          0
20   Ramesh
22   Suresh
24  Sathish

In [10]:
names=['Ramesh','Suresh','Sathish']
age=[20,22,24]
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
#pd.Dataframe(data,index,columns)
df

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

**Step-7: Add a new column to already existed df**

- in above first we have taken data 

- then created a dataframe

- now we want to add new data based on requirement

In [12]:
city=['Hyd','Pune','Vizag']
df['City']=city
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [13]:
city=['Hyd','Pune','Vizag']
df['Country']=city
df

     Names  Age   City Country
0   Ramesh   20    Hyd     Hyd
1   Suresh   22   Pune    Pune
2  Sathish   24  Vizag   Vizag

In [16]:
df['Marks']=[20,30,40]
df

     Names  Age   City Country  Marks
0   Ramesh   20    Hyd     Hyd     20
1   Suresh   22   Pune    Pune     30
2  Sathish   24  Vizag   Vizag     40

**Step-8: Update the column with new values**

In [18]:
df['Marks']=[200,300,400]
#selection means square braces
#function means braces

In [19]:
df   #updating and creating the column is same

     Names  Age   City Country  Marks
0   Ramesh   20    Hyd     Hyd    200
1   Suresh   22   Pune    Pune    300
2  Sathish   24  Vizag   Vizag    400

**Step-9: create empty dataframe and add the columns**

In [20]:
#empty dataframe
df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [21]:
#adding columns
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Pune','Vizag']
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

**Step-10: Create a df using dictionary**

In [23]:
d={'Names':['Ramesh','Suresh','Sathish'],
'Age':[20,22,24],
'City':['Hyd','Pune','Vizag']}
df=pd.DataFrame(d)
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [24]:
d={'Name':'Ramesh',
  'Age':20}
pd.DataFrame(d)

ValueError: If using all scalar values, you must pass an index

In [25]:
#scalar->single value->no direction
#vector->two values->direction->array

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [26]:
d={'Name':'Ramesh',
  'Age':20}
pd.DataFrame(d,index=[0])

     Name  Age
0  Ramesh   20

**Step-11: saving the dataframe(df)**

In [28]:
#file handling session
#directory//filename.ext
#filename.ext
#we are saving data frames in
#     .csv  or  .xlsx

df.to_csv('data.csv')

In [29]:
df.to_excel('data.xlsx')

**Step-12: How to read the df**

In [2]:
#in oreder to read the data 
#filename.ext
#open(mobox-short.txt).read()
#open(dummy.txt,mode='w').write('hello')

#data.csv        data.xlsx
pd.read_csv('data.csv')

   Unnamed: 0    Names  Age   City
0           0   Ramesh   20    Hyd
1           1   Suresh   22   Pune
2           2  Sathish   24  Vizag

In [3]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Sathish']
df['Age']=[20,22,24]
df['City']=['Hyd','Pune','Vizag']
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [4]:
pd.read_excel('data.xlsx')

   Unnamed: 0    Names  Age   City
0           0   Ramesh   20    Hyd
1           1   Suresh   22   Pune
2           2  Sathish   24  Vizag

In [5]:
d={'Names':['Ramesh','Suresh','Sathish'],
'Age':[20,22,24],
'City':['Hyd','Pune','Vizag']}
df=pd.DataFrame(d)
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [ ]:
df.to_csv
pd.read_csv

df.to_excel
pd.read_excel

In [6]:
df.to_csv('data1.csv',index=False)

In [8]:
pd.read_csv('data1.csv')

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [9]:
df.to_excel('data1.xlsx',index=False)

In [10]:
pd.read_excel('data1.xlsx')

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [18]:
#add one more column marks using df
d={'Names':['Ramesh','Suresh','Sathish'],
'Age':[20,22,24],
'City':['Hyd','Pune','Vizag'],
'Marks':[200,300,400]}
df=pd.DataFrame(d)
df

     Names  Age   City  Marks
0   Ramesh   20    Hyd    200
1   Suresh   22   Pune    300
2  Sathish   24  Vizag    400

In [13]:
df['Marks']=[20,30,40]
df

     Names  Age   City  Marks
0   Ramesh   20    Hyd     20
1   Suresh   22   Pune     30
2  Sathish   24  Vizag     40

**Step-13: Drop the column**

- labels
    
- axis
    
- index
    
- columns
    
- level
    
- inplace

In [15]:
#if i want to drop a index
df.drop()

<bound method DataFrame.drop of      Names  Age   City  Marks
0   Ramesh   20    Hyd     20
1   Suresh   22   Pune     30
2  Sathish   24  Vizag     40>

In [21]:
df.drop(index=1)

     Names  Age   City  Marks
0   Ramesh   20    Hyd    200
2  Sathish   24  Vizag    400

In [22]:
df.drop(columns='Marks')

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [23]:
df.drop(columns=['Marks','City'])

     Names  Age
0   Ramesh   20
1   Suresh   22
2  Sathish   24

In [ ]:
df.drop(index=1)
df.drop(columns='Marks')

#=============================================

df.drop('marks') #if i dont give argument label
df.drop(1)   #i become label

#================================================

# we need to provide axis
# axis=0 indicates index
# axis=1 indicates columns

In [26]:
df.drop('Marks',axis=0)

KeyError: "['Marks'] not found in axis"

In [25]:
df.drop('Marks',axis=1)

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

**inplace**

- when we do the operation the result output is not overwriting

- means the original dataframe is same as it is.

- in order to do this we need to use **inplace**

- by default inplace=False

-  if you want to make **inplace=True** if you want to overwrite the result

In [27]:
df.drop('Marks',axis=1,inplace=True)

In [28]:
df

     Names  Age   City
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

**Step-14: Rename the column**

In [34]:
d={'City':'city'} #{old:new}
#df.rename(<mapper>,<axis>,<inplace>)
df.rename(d,axis=1,inplace=True)
df

     Names  Age   city
0   Ramesh   20    Hyd
1   Suresh   22   Pune
2  Sathish   24  Vizag

In [35]:
d={2:'B'}
df.rename(d,axis=0,inplace=True)
df

     Names  Age   city
0   Ramesh   20    Hyd
1   Suresh   22   Pune
B  Sathish   24  Vizag

In [39]:
## Create one more df
# x=1 to 10
# y= square x
# z=c cube x

In [40]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x ]
df=pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])
df

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

**Methods**

- len

- shape : df.shape

- head  : df.head

- tail  : df.tail

- isnull : df.isnull

- dtypes : df.types

- info   : df.info

In [45]:
len(df)

10

In [53]:
df.shape  # 10 rows 3 cols

(10, 3)

In [54]:
df.size

30

In [48]:
df.head()

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [47]:
df.tail()

    X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [49]:
df.isnull()

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [50]:
df.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

In [51]:
df.dtypes
#if any categorical columns occures
#it represent as object
#int==>int64

X    int64
Y    int64
Z    int64
dtype: object

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

**Step-15: select a columns**

In [55]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [56]:
df['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [58]:
df[['X','Y']]  #10 rows 2 cols ===>(10,2)-->2D two lists needed-->creating dataframe

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [59]:
type(df['X'])
# 1d-->single variable
# 1 list

pandas.core.series.Series

In [60]:
type(df[['X','Y']])
# 2D-->two variables
# 2 lists

pandas.core.frame.DataFrame

In [61]:
df['X'].shape

(10,)

In [62]:
df[['X','Y']].shape

(10, 2)

In [65]:
df    #dataframe
df['X']  # selecting one particular column
df['X'].values  # extracting the data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [68]:
df    #dataframe
df['Z']  # selecting one particular column
df['Z'].values  # extracting the data
df['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [66]:
df
df[['Y','Z']]
df[['Y','Z']].values

array([[   1,    1],
       [   4,    8],
       [   9,   27],
       [  16,   64],
       [  25,  125],
       [  36,  216],
       [  49,  343],
       [  64,  512],
       [  81,  729],
       [ 100, 1000]])

In [69]:
df
df[['Y','Z']]
df[['Y','Z']].values.tolist()

[[1, 1],
 [4, 8],
 [9, 27],
 [16, 64],
 [25, 125],
 [36, 216],
 [49, 343],
 [64, 512],
 [81, 729],
 [100, 1000]]