**Feature Engineering**

- So far we have performed feature analysis

   - Data frame quick checks

   - Categorical column analysis

   - Bar charts,pie charts

   - Numerical column analysis

   - Histograms, box plots, outliers

   - Bi-multi variant analysis  

   - correlation etc

- Now we need to learn Feature Engineering

   - we will create a new columns for better ML models

   - we will perform the **Encoding**,which is convert Categorical to Numerical columns

   - we will do data **transformations**

   - we will perform **Scaling: Standarization and Normalisation**

   - we will perform the **missing value analysis**

- Simply feature engineering means our data will be modified

- Feature Analysis

- Feature Engineering

- Feature Selection

- Model Development

- Model Evaluation/testing

- Model tuning

- Model Deployment

**Encoding**

- Encoding means convert categorical data to Numerical data

- ML/DL or any models works based on mathematics(maths)

- Model cannot understand english characters 

- So it is very important to convert categorical label to Numerical values

- For example Gender column has two labels

  - Male

  - Female

- Then Female represent as 0, Male represent as 1 based on alphabetical order

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [14]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,Denied
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,Certified
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,Denied
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,Denied
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,Certified
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,Certified
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,Certified
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,Certified
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,Certified
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,Certified

In [15]:
cat=visa_df.select_dtypes(include='object').columns
cat

Index(['case_id', 'continent', 'education_of_employee', 'has_job_experience',
       'requires_job_training', 'region_of_employment', 'unit_of_wage',
       'full_time_position', 'case_status'],
      dtype='object')

In [16]:
num=visa_df.select_dtypes(exclude='object').columns
num

Index(['no_of_employees', 'yr_of_estab', 'prevailing_wage'], dtype='object')

In [17]:
visa_df['case_status'].unique()

array(['Denied', 'Certified'], dtype=object)

- Certified should assign as 0

- Denied should assign as 1

In [18]:
#mapping
d={'Certified':0,'Denied':1}
d

{'Certified': 0, 'Denied': 1}

In [19]:
visa_df['case_status']=visa_df['case_status'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [13]:
visa_df['continent'].unique()

array(['Asia', 'Africa', 'North America', 'Europe', 'South America',
       'Oceania'], dtype=object)

In [20]:
d={}
d['Asia']=0
d['Africa']=1
d['North America']=2
d['Europe']=3
d['South America']=4
d[ 'Oceania']=5
d

{'Asia': 0,
 'Africa': 1,
 'North America': 2,
 'Europe': 3,
 'South America': 4,
 'Oceania': 5}

In [24]:
labels=visa_df['continent'].unique()
n=len(labels)
d={}
for i in range(n):
    print(labels[i],i)

Asia 0
Africa 1
North America 2
Europe 3
South America 4
Oceania 5

In [29]:
# method-1
labels=sorted(visa_df['continent'].unique())
n=len(labels)
d={}
for i in range(n):
    d[labels[i]]=i
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [28]:
#method-2
labels=sorted(visa_df['continent'].unique())
d={}
for i,j in enumerate(labels):
    d[j]=i
d

{'Africa': 0,
 'Asia': 1,
 'Europe': 2,
 'North America': 3,
 'Oceania': 4,
 'South America': 5}

In [32]:
# method 3: list comprehension
labels=sorted(visa_df['continent'].unique())
d={j:i for i,j in enumerate(labels)}
d

{np.int64(0): 0,
 np.int64(1): 1,
 np.int64(2): 2,
 np.int64(3): 3,
 np.int64(4): 4,
 np.int64(5): 5}

In [34]:
l=['apple','banana']
for i in range(len(l)):
    print(i,l[i])

0 apple
1 banana

In [35]:
for i,j in enumerate(l):
    print(i,j)

0 apple
1 banana

In [30]:
visa_df['continent']=visa_df['continent'].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [ ]:
# step-1: read the data
# step-2 : get the cat columns

In [40]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns
for i in cat:
   labels=sorted(visa_df[i].unique())
   d={j:i for i,j in enumerate(labels)}
   visa_df[i]=visa_df[i].map(d)
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,0,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,1,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,2,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,3,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,4,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,17204,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,17205,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,17206,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,17207,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,17209,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**LableEncoder**

- LableEncoder is a  method will convert cat labels to numerical values

- It is under package:**sklearn(scikit-learn)**

   - The class Name:**preprocessing**

        - The metghod name:**LableEncoder**

In [ ]:
#syntax
from <package>.<class> import <method>

In [41]:
from sklearn.preprocessing import LabelEncoder

- step-1: import the method

- step-2: save the method

- step-3: apply fit transform

- **fit transform**

   - **fit**: means find the logic

       - in above example fit means create a **mapper** or **dict**

   - **transform**:apply the logic and change the data

       - apply the **mapper on the data**

In [45]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

# Import the method
from sklearn.preprocessing import LabelEncoder

# save the method
le=LabelEncoder()

# apply fir transform
visa_df['case_status']=le.fit_transform(visa_df['case_status'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,Asia,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,Asia,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,Asia,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,Asia,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,Africa,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,Asia,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,Asia,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,Asia,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,Asia,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,Asia,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [48]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
#le.fit_transform()
visa_df['continent']=le.fit_transform(visa_df['continent'])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,High School,N,N,14513,2007,West,592.2029,Hour,Y,1
1,EZYV02,1,Master's,Y,N,2412,2002,Northeast,83425.6500,Year,Y,0
2,EZYV03,1,Bachelor's,N,Y,44444,2008,West,122996.8600,Year,Y,1
3,EZYV04,1,Bachelor's,N,N,98,1897,West,83434.0300,Year,Y,1
4,EZYV05,0,Master's,Y,N,1082,2005,South,149907.3900,Year,Y,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,Bachelor's,Y,Y,2601,2008,South,77092.5700,Year,Y,0
25476,EZYV25477,1,High School,Y,N,3274,2006,Northeast,279174.7900,Year,Y,0
25477,EZYV25478,1,Master's,Y,N,1121,1910,South,146298.8500,Year,N,0
25478,EZYV25479,1,Master's,Y,Y,1918,1887,West,86154.7700,Year,Y,0
25479,EZYV25480,1,Bachelor's,Y,N,3195,1960,Midwest,70876.9100,Year,Y,0

In [49]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns
from sklearn.preprocessing import LabelEncoder
for i in cat[1:]:
      le=LabelEncoder()
      visa_df[i]=le.fit_transform(visa_df[i])
visa_df

,case_id,continent,education_of_employee,has_job_experience,requires_job_training,no_of_employees,yr_of_estab,region_of_employment,prevailing_wage,unit_of_wage,full_time_position,case_status
0,EZYV01,1,2,0,0,14513,2007,4,592.2029,0,1,1
1,EZYV02,1,3,1,0,2412,2002,2,83425.6500,3,1,0
2,EZYV03,1,0,0,1,44444,2008,4,122996.8600,3,1,1
3,EZYV04,1,0,0,0,98,1897,4,83434.0300,3,1,1
4,EZYV05,0,3,1,0,1082,2005,3,149907.3900,3,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
25475,EZYV25476,1,0,1,1,2601,2008,3,77092.5700,3,1,0
25476,EZYV25477,1,2,1,0,3274,2006,2,279174.7900,3,1,0
25477,EZYV25478,1,3,1,0,1121,1910,3,146298.8500,3,0,0
25478,EZYV25479,1,3,1,1,1918,1887,4,86154.7700,3,1,0
25479,EZYV25480,1,0,1,0,3195,1960,1,70876.9100,3,1,0

**OneHotEncoder**

- First check how many lables are there in a columns

- That many new columns will be created extra

- For example case status has two lables

   - Certified

   - Denied

- So it will create Two  new extra columns

  - case_status_Certified

  - case_status_Denied

- At a time one column value become 1 other column value become 0

- This means a **one hot encoder**

|case_status|case_status_Certified|case_status_Denied
|-|-|-|
|Certified|1|0
|Denied|0|1
|Denied|0|1
|Certified|1|0

In [50]:
# continent       C_A   C_Af   C_E
# Asia             1      0     0
# Africa           0      1     0
# Europe           0      0     1

**pd.get_dummies**

In [57]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['case_status'])

       Certified  Denied
0          False    True
1           True   False
2          False    True
3          False    True
4           True   False
...          ...     ...
25475       True   False
25476       True   False
25477       True   False
25478       True   False
25479       True   False

[25480 rows x 2 columns]

In [56]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['case_status'],dtype=int)

       Certified  Denied
0              0       1
1              1       0
2              0       1
3              0       1
4              1       0
...          ...     ...
25475          1       0
25476          1       0
25477          1       0
25478          1       0
25479          1       0

[25480 rows x 2 columns]

In [55]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['continent'])

       Africa   Asia  Europe  North America  Oceania  South America
0       False   True   False          False    False          False
1       False   True   False          False    False          False
2       False   True   False          False    False          False
3       False   True   False          False    False          False
4        True  False   False          False    False          False
...       ...    ...     ...            ...      ...            ...
25475   False   True   False          False    False          False
25476   False   True   False          False    False          False
25477   False   True   False          False    False          False
25478   False   True   False          False    False          False
25479   False   True   False          False    False          False

[25480 rows x 6 columns]

In [54]:
file_path=r"C:\Users\91801\Documents\Data_Files\Visadataset.csv"
visa_df=pd.read_csv(file_path)
cat=visa_df.select_dtypes(include='object').columns

pd.get_dummies(visa_df['continent'],dtype=int)

       Africa  Asia  Europe  North America  Oceania  South America
0           0     1       0              0        0              0
1           0     1       0              0        0              0
2           0     1       0              0        0              0
3           0     1       0              0        0              0
4           1     0       0              0        0              0
...       ...   ...     ...            ...      ...            ...
25475       0     1       0              0        0              0
25476       0     1       0              0        0              0
25477       0     1       0              0        0              0
25478       0     1       0              0        0              0
25479       0     1       0              0        0              0

[25480 rows x 6 columns]

In [ ]:
q) what is Encoding?