In [3]:
import pandas as pd
import numpy as np

dict1={'Names':['Ramesh','Suresh','Sathish',np.nan],
       'Age':[np.nan,22,24,26],
      'City':['Hyd','Blr',np.nan,'Vizag']}
d1=pd.DataFrame(dict1)
d1.to_csv('data1.csv',index=False)

In [4]:
import pandas as pd
import numpy as np

dict2={'Names':['Ramesh','Suresh','Sathish',None],
       'Age':[None,22,24,26],
      'City':['Hyd','Blr',None,'Vizag']}
d2=pd.DataFrame(dict2)
d2.to_csv('data2.csv',index=False)

In [5]:
d1.isnull()

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False   True
3   True  False  False

In [10]:
d1.isnull().sum()

Names    1
Age      1
City     1
dtype: int64

**Difference between NAN and None**

- For **Object Type** we use **None**

- For **Number Type** we will use **NAN**

In [11]:
np.nan+5

nan

In [12]:
None+5

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [13]:
arr1=np.array([1,2,3,np.nan])
arr2=np.array([1,2,3,None])
arr1

array([ 1.,  2.,  3., nan])

In [14]:
arr2

array([1, 2, 3, None], dtype=object)

In [20]:
arr1.dtype,arr2.dtype

(dtype('float64'), dtype('O'))

In [19]:
np.sum(arr1),np.nansum(arr1)
#1+2+3+mp.nam     1+2+3

(np.float64(nan), np.float64(6.0))

In [21]:
np.sum(arr2) # error because of object type

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [22]:
arr2 # object type this is my mistake
# how can we convert into float type

array([1, 2, 3, None], dtype=object)

**astype**

In [23]:
arr3=arr2.astype(float) 
arr3

array([ 1.,  2.,  3., nan])

In [24]:
d2['Age'].values.astype(int) # to convert to another data type completely

C:\Users\91801\AppData\Local\Temp\ipykernel_14024\3751503362.py:1: RuntimeWarning: invalid value encountered in cast
  d2['Age'].values.astype(int)

array([-9223372036854775808,                   22,                   24,
                         26])

**Fill with a random value**

In [25]:
d1.fillna(30) # bad approach not recommended because names also filled with 30
# inplace=True

     Names   Age   City
0   Ramesh  30.0    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0     30
3       30  26.0  Vizag

In [26]:
d1

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    NaN
3      NaN  26.0  Vizag

**fill with a random value based on column**

In [28]:
# based on the column we fill it
# first select the colums
d1['Age'].fillna(30)
#d1['Age']=d1['Age'].fillna(30)

0    30.0
1    22.0
2    24.0
3    26.0
Name: Age, dtype: float64

**By using methods**

- pad

- ffill

- bfill

- backfill

In [29]:
d1.fillna(method='pad')

C:\Users\91801\AppData\Local\Temp\ipykernel_14024\3282249208.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  d1.fillna(method='pad')

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    Blr
3  Sathish  26.0  Vizag

In [31]:
# to ignore the warnings
import warnings
warnings.filterwarnings('ignore')
d1.fillna(method='pad')

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    Blr
3  Sathish  26.0  Vizag

In [39]:
d1

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    NaN
3      NaN  26.0  Vizag

In [36]:
d1.fillna(method='pad',axis=0)

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    Blr
3  Sathish  26.0  Vizag

In [40]:
d1.fillna(method='ffill')

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    Blr
3  Sathish  26.0  Vizag

In [37]:
d1.fillna(method='bfill')

     Names   Age   City
0   Ramesh  22.0    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0  Vizag
3      NaN  26.0  Vizag

In [38]:
d1.fillna(method='backfill')

     Names   Age   City
0   Ramesh  22.0    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0  Vizag
3      NaN  26.0  Vizag

**Mean-Median-Mode**

- when data has outliers go with **Median**

- Otherwise fill with **Mean**

- For a categorical data fill with **Mode**

In [41]:
age_mean=d1['Age'].mean()
d1['Age'].fillna(age_mean)

0    24.0
1    22.0
2    24.0
3    26.0
Name: Age, dtype: float64

In [44]:
0d1['City'].mode()

0      Blr
1      Hyd
2    Vizag
Name: City, dtype: object

In [49]:
len(d1)

4

In [51]:
new_row={'Names':'Sathish','Age':24,'City':'Vizag'}
d1.loc[len(d1)]=new_row
d1

     Names   Age   City
0   Ramesh   NaN    Hyd
1   Suresh  22.0    Blr
2  Sathish  24.0    NaN
3      NaN  26.0  Vizag
4  Sathish  24.0  Vizag
5  Sathish  24.0  Vizag

In [57]:
d1['City'].mode().values[0]

'Vizag'

In [56]:
d1  # df
d1['City'] # select the data
d1['City'].mode()
d1['City'].mode().values  # series will come if uu use values
city_mode=d1['City'].mode().values[0]
d1['City'].fillna(city_mode)

0      Hyd
1      Blr
2    Vizag
3    Vizag
4    Vizag
5    Vizag
Name: City, dtype: object

In [53]:
d1['Age'].mean()

np.float64(24.0)